---
abstract: 'Parent class for Logic minimizers like Quine-McCluskey'
author:
  - 'John M. Gamble <jgamble@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  List::MoreUtils: '0.401'
  Module::Build: '0'
dynamic_config: 0
generated_by: 'Module::Build version 0.4218, CPAN::Meta::Converter version 2.150005'
keywords:
  - boolean
  - boolean-algebra
  - logic
  - truth-tables
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Logic-Minimizer
provides:
  Logic::Minimizer:
    file: lib/Logic/Minimizer.pm
    version: '1.00'
requires:
  Carp: '0'
  List::MoreUtils: '0.401'
  Moose: '2.16'
  namespace::autoclean: '0.16'
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jgamble/Logic-Minimizer
version: '1.00'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
